### ISSUE TITLE
New 0.9.0 release fails when load predictors

### ISSUE THREAD

**Issue by EstiGascon** [esowc/ecPoint-Calibrate#118]
The new 0.9.0 works fine for me, however when I try load the folder with the predictors, it appears a "blank page" and it does not work anymore. I have the following messages in the console (only the last line appears when I try to load the predictors, the previous ones are already before that:

(docker) moeg@carmina:~/ecpoint/Calibration/Python_GUI> ./ecPoint-Calibrate-0.9.0.AppImage 
Fontconfig warning: "/etc/fonts/fonts.conf", line 86: unknown element "blank"
Pulling from onyb/ecpoint-calibrate-logger
Digest: sha256:a4208ddd5336fe9f007c5f1d462ef18018d6276ebf4cb14eedd3b58a0e40a2a3
Status: Image is up to date for onyb/ecpoint-calibrate-logger:latest
Pulling from onyb/ecpoint-calibrate-core
Digest: sha256:8fade9a17be9022705762242e8fec7e037bbf5b4210cd3469d5afbba6cf63d8e
Status: Image is up to date for onyb/ecpoint-calibrate-core:develop
Running Docker container: image=onyb/ecpoint-calibrate-logger containerID=d115dcf78283
Running Docker container: image=onyb/ecpoint-calibrate-core:develop containerID=fc4c9e90c374
 * Serving Flask app "api" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:8888/ (Press CTRL+C to quit)
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.

**Comment by onyb** [comment]
Some questions:
* What is the path of your folder with predictors?
* Does restarting the software fix the problem?

Can you also please go to "View > Toggle Developer Tools" on the GUI, and paste all that you see on the console?

**Comment by FatimaPillosu** [comment]
I'm having the same problem.
The problem does not get fixed when I restart the software.
The paths is /vol/ecpoint/mofp/calibrations/InputDB/Rainfall/ECMWF_ENS_47r1/FC/
and the directories with the names of the predictors are in there (e.g. cape, tp, cp, etc.)

This is what appears when I opening the console in the toggle:
﻿
Download the React DevTools for a better development experience: https://fb.me/react-devtools
You might need to use a local HTTP server (instead of file://): https://fb.me/react-devtools-faq
checkPropTypes.js:20 Warning: Failed prop type: Given props { icon: "edit outline" }: Prop `children` in `Button` conflicts with props: `icon`. They cannot be defined together, choose one or the other.
    in Button (created by App)
    in App (created by ConnectFunction)
    in ConnectFunction (created by Context.Consumer)
    in Route (created by Root)
    in Switch (created by Root)
    in Router (created by HashRouter)
    in HashRouter (created by Root)
    in Root
    in PersistGate
    in Provider
checkPropTypes.js:20 Warning: Failed prop type: Given props { icon: "lab" }: Prop `children` in `Button` conflicts with props: `icon`. They cannot be defined together, choose one or the other.
    in Button (created by App)
    in App (created by ConnectFunction)
    in ConnectFunction (created by Context.Consumer)
    in Route (created by Root)
    in Switch (created by Root)
    in Router (created by HashRouter)
    in HashRouter (created by Root)
    in Root
    in PersistGate
    in Provider
checkPropTypes.js:20 Warning: Failed prop type: Invalid prop `color` of value `github` supplied to `Button`, expected one of ["red","orange","yellow","olive","green","teal","blue","violet","purple","pink","brown","grey","black","facebook","google plus","instagram","linkedin","twitter","vk","youtube"].
    in Button (created by App)
    in App (created by ConnectFunction)
    in ConnectFunction (created by Context.Consumer)
    in Route (created by Root)
    in Switch (created by Root)
    in Router (created by HashRouter)
    in HashRouter (created by Root)
    in Root
    in PersistGate
    in Provider
react-dom.development.js:88 Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: Portal
react-dom.development.js:88 Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: Checkbox
component.js:58 Uncaught TypeError: _this.props.predictors.codes.map is not a function
    at Predictors.eval [as getField] (component.js:58)
    at Predictors.render (component.js:124)
    at finishClassComponent (react-dom.development.js:17160)
    at updateClassComponent (react-dom.development.js:17110)
    at beginWork (react-dom.development.js:18620)
    at HTMLUnknownElement.callCallback (react-dom.development.js:188)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:237)
    at invokeGuardedCallback (react-dom.development.js:292)
    at beginWork$1 (react-dom.development.js:23203)
    at performUnitOfWork (react-dom.development.js:22157)
react-dom.development.js:19527 The above error occurred in the <Predictors> component:
    in Predictors (created by ConnectFunction)
    in ConnectFunction (created by Page1)
    in Page1 (created by Page)
    in Page (created by ConnectFunction)
    in ConnectFunction (created by App)
    in App (created by ConnectFunction)
    in ConnectFunction (created by Context.Consumer)
    in Route (created by Root)
    in Switch (created by Root)
    in Router (created by HashRouter)
    in HashRouter (created by Root)
    in Root
    in PersistGate
    in Provider

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
react-dom.development.js:11102 Uncaught TypeError: _this.props.predictors.codes.map is not a function
    at Predictors.eval [as getField] (component.js:58)
    at Predictors.render (component.js:124)
    at finishClassComponent (react-dom.development.js:17160)
    at updateClassComponent (react-dom.development.js:17110)
    at beginWork (react-dom.development.js:18620)
    at HTMLUnknownElement.callCallback (react-dom.development.js:188)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:237)
    at invokeGuardedCallback (react-dom.development.js:292)
    at beginWork$1 (react-dom.development.js:23203)
    at performUnitOfWork (react-dom.development.js:22157)
DevTools failed to load SourceMap: Could not load content for webpack:///node_modules/react-router-dom/esm/react-router-dom.js.map: 
DevTools failed to load SourceMap: Could not load content for webpack:///node_modules/react-router/esm/react-router.js.map: 
DevTools failed to load SourceMap: Could not load content for webpack:///node_modules/uri-js/dist/es5/uri.all.js.map: 
DevTools failed to load SourceMap: Could not load content for webpack:///node_modules/performance-now/lib/performance-now.js.map: 
DevTools failed to load SourceMap: Could not load content for webpack:///node_modules/popper.js/dist/esm/popper.js.map:

**Comment by EstiGascon** [comment]
- The path of my folders is the typical /vol/ system, in my case "/vol/highlander/ecPoint_Calibrate_InDB/ecPoint_Temperature/ECMWF_41r2_anERA5/AN"
- Restarting the software does not fix the problem. Fatima also tried to load the same database and she had the same problem. 
- It is important to point out tha**t I can load this database with the old version,** so I am currently working with it, 

These are the messages from **Toggle Developer Tools**
Download the React DevTools for a better development experience: https://fb.me/react-devtoolsYou might need to use a local HTTP server (instead of file://): https://fb.me/react-devtools-faq
checkPropTypes.js:20 Warning: Failed prop type: Given props { icon: "edit outline" }: Prop `children` in `Button` conflicts with props: `icon`. They cannot be defined together, choose one or the other.
    in Button (created by App)
    in App (created by ConnectFunction)
    in ConnectFunction (created by Context.Consumer)
    in Route (created by Root)
    in Switch (created by Root)
    in Router (created by HashRouter)
    in HashRouter (created by Root)
    in Root
    in PersistGate
    in Provider
printWarning @ checkPropTypes.js:20
checkPropTypes.js:20 Warning: Failed prop type: Given props { icon: "lab" }: Prop `children` in `Button` conflicts with props: `icon`. They cannot be defined together, choose one or the other.
    in Button (created by App)
    in App (created by ConnectFunction)
    in ConnectFunction (created by Context.Consumer)
    in Route (created by Root)
    in Switch (created by Root)
    in Router (created by HashRouter)
    in HashRouter (created by Root)
    in Root
    in PersistGate
    in Provider
printWarning @ checkPropTypes.js:20
checkPropTypes.js:20 Warning: Failed prop type: Invalid prop `color` of value `github` supplied to `Button`, expected one of ["red","orange","yellow","olive","green","teal","blue","violet","purple","pink","brown","grey","black","facebook","google plus","instagram","linkedin","twitter","vk","youtube"].
    in Button (created by App)
    in App (created by ConnectFunction)
    in ConnectFunction (created by Context.Consumer)
    in Route (created by Root)
    in Switch (created by Root)
    in Router (created by HashRouter)
    in HashRouter (created by Root)
    in Root
    in PersistGate
    in Provider
printWarning @ checkPropTypes.js:20
react-dom.development.js:88 Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: Portal
printWarning @ react-dom.development.js:88
react-dom.development.js:88 Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: Checkbox
printWarning @ react-dom.development.js:88
component.js:58 Uncaught TypeError: _this.props.predictors.codes.map is not a function
    at Predictors.eval [as getField] (component.js:58)
    at Predictors.render (component.js:124)
    at finishClassComponent (react-dom.development.js:17160)
    at updateClassComponent (react-dom.development.js:17110)
    at beginWork (react-dom.development.js:18620)
    at HTMLUnknownElement.callCallback (react-dom.development.js:188)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:237)
    at invokeGuardedCallback (react-dom.development.js:292)
    at beginWork$1 (react-dom.development.js:23203)
    at performUnitOfWork (react-dom.development.js:22157)
react-dom.development.js:19527 The above error occurred in the <Predictors> component:
    in Predictors (created by ConnectFunction)
    in ConnectFunction (created by Page1)
    in Page1 (created by Page)
    in Page (created by ConnectFunction)
    in ConnectFunction (created by App)
    in App (created by ConnectFunction)
    in ConnectFunction (created by Context.Consumer)
    in Route (created by Root)
    in Switch (created by Root)
    in Router (created by HashRouter)
    in HashRouter (created by Root)
    in Root
    in PersistGate
    in Provider

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
logCapturedError @ react-dom.development.js:19527
react-dom.development.js:11102 Uncaught TypeError: _this.props.predictors.codes.map is not a function
    at Predictors.eval [as getField] (component.js:58)
    at Predictors.render (component.js:124)
    at finishClassComponent (react-dom.development.js:17160)
    at updateClassComponent (react-dom.development.js:17110)
    at beginWork (react-dom.development.js:18620)
    at HTMLUnknownElement.callCallback (react-dom.development.js:188)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:237)
    at invokeGuardedCallback (react-dom.development.js:292)
    at beginWork$1 (react-dom.development.js:23203)
    at performUnitOfWork (react-dom.development.js:22157)
DevTools failed to load SourceMap: Could not load content for webpack:///node_modules/react-router-dom/esm/react-router-dom.js.map: 
DevTools failed to load SourceMap: Could not load content for webpack:///node_modules/react-router/esm/react-router.js.map: 
DevTools failed to load SourceMap: Could not load content for webpack:///node_modules/uri-js/dist/es5/uri.all.js.map: 
DevTools failed to load SourceMap: Could not load content for webpack:///node_modules/performance-now/lib/performance-now.js.map: 
DevTools failed to load SourceMap: Could not load content for webpack:///node_modules/popper.js/dist/esm/popper.js.map:

**Comment by onyb** [comment]
Thanks for the logs! I think I found the bug. It's because `/vol` (which is where all your datasets reside) is not recognized by the software anymore. I assumed it was `/media`, which is not the case with you.

I'm going to issue a fix this evening, and also handle the case of unknown paths crashing the software in future.

**Comment by onyb** [comment]
Fixed in 8d0ff73705771bba986d35e2900cb2197bd9f471. Will be part of the **v0.10.0** release. Backwards compatibility is added for v0.9.0 to continue working with the new version of the backend.

**Comment by FatimaPillosu** [comment]
Hi @onyb ,
when v0.10.0 will be released? 
Esti and Augustin can work with the older version, but it would be better if they could use the newer version as soon as possible.
Cheers,
Fatima

**Comment by FatimaPillosu** [comment]
Hi @onyb ,
I think the problem has not been solved. The screen becomes blank again when I select the predictors.

------------------------
This what I get in the console:

Fontconfig warning: "/etc/fonts/fonts.conf", line 86: unknown element "blank"
Pulling from onyb/ecpoint-calibrate-logger
Digest: sha256:2238a96fe114e3a8dc638175ed9c92d336da6b3b73394d6786554f9201b27ea9
Status: Image is up to date for onyb/ecpoint-calibrate-logger:0.10.0
Pulling from onyb/ecpoint-calibrate-core
Digest: sha256:4c4512afa63a419b213151e3764cd20caea0187ddb410fd8da325727da97bac9
Status: Image is up to date for onyb/ecpoint-calibrate-core:0.10.0
Running Docker container: image=onyb/ecpoint-calibrate-logger:0.10.0 containerID=8856b3bfd3b3
Running Docker container: image=onyb/ecpoint-calibrate-core:0.10.0 containerID=9b08706ffb00
 * Serving Flask app "api" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:8888/ (Press CTRL+C to quit)
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.

--------------------------------------------------------------------------------------

This is what I get in the toggle:

webpack:///../node_m…eckPropTypes.js?:20 Warning: Failed prop type: Given props { icon: "lab" }: Prop `children` in `Button` conflicts with props: `icon`. They cannot be defined together, choose one or the other.
    in Button (created by App)
    in App (created by ConnectFunction)
    in ConnectFunction (created by Context.Consumer)
    in Route (created by Root)
    in Switch (created by Root)
    in Router (created by HashRouter)
    in HashRouter (created by Root)
    in Root
    in PersistGate
    in Provider
webpack:///../node_m…eckPropTypes.js?:20 Warning: Failed prop type: Invalid prop `color` of value `github` supplied to `Button`, expected one of ["red","orange","yellow","olive","green","teal","blue","violet","purple","pink","brown","grey","black","facebook","google plus","instagram","linkedin","twitter","vk","youtube"].
    in Button (created by App)
    in App (created by ConnectFunction)
    in ConnectFunction (created by Context.Consumer)
    in Route (created by Root)
    in Switch (created by Root)
    in Router (created by HashRouter)
    in HashRouter (created by Root)
    in Root
    in PersistGate
    in Provider
webpack:///../node_m….development.js?:88 Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: Portal
webpack:///../node_m….development.js?:88 Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: Checkbox
webpack:///./workflo…rs/component.js?:58 Uncaught TypeError: _this.props.predictors.codes.map is not a function
    at Predictors.eval [as getField] (webpack:///./workflo…rs/component.js?:58)
    at Predictors.render (webpack:///./workflo…s/component.js?:124)
    at finishClassComponent (webpack:///../node_m…velopment.js?:17160)
    at updateClassComponent (webpack:///../node_m…velopment.js?:17110)
    at beginWork (webpack:///../node_m…velopment.js?:18620)
    at HTMLUnknownElement.callCallback (webpack:///../node_m…development.js?:188)
    at Object.invokeGuardedCallbackDev (webpack:///../node_m…development.js?:237)
    at invokeGuardedCallback (webpack:///../node_m…development.js?:292)
    at beginWork$1 (webpack:///../node_m…velopment.js?:23203)
    at performUnitOfWork (webpack:///../node_m…velopment.js?:22157)
webpack:///../node_m…velopment.js?:19527 The above error occurred in the <Predictors> component:
    in Predictors (created by ConnectFunction)
    in ConnectFunction (created by Page1)
    in Page1 (created by Page)
    in Page (created by ConnectFunction)
    in ConnectFunction (created by App)
    in App (created by ConnectFunction)
    in ConnectFunction (created by Context.Consumer)
    in Route (created by Root)
    in Switch (created by Root)
    in Router (created by HashRouter)
    in HashRouter (created by Root)
    in Root
    in PersistGate
    in Provider

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
webpack:///../node_m…velopment.js?:11102 Uncaught TypeError: _this.props.predictors.codes.map is not a function
    at Predictors.eval [as getField] (webpack:///./workflo…rs/component.js?:58)
    at Predictors.render (webpack:///./workflo…s/component.js?:124)
    at finishClassComponent (webpack:///../node_m…velopment.js?:17160)
    at updateClassComponent (webpack:///../node_m…velopment.js?:17110)
    at beginWork (webpack:///../node_m…velopment.js?:18620)
    at HTMLUnknownElement.callCallback (webpack:///../node_m…development.js?:188)
    at Object.invokeGuardedCallbackDev (webpack:///../node_m…development.js?:237)
    at invokeGuardedCallback (webpack:///../node_m…development.js?:292)
    at beginWork$1 (webpack:///../node_m…velopment.js?:23203)
    at performUnitOfWork (webpack:///../node_m…velopment.js?:22157)
DevTools failed to load SourceMap: Could not load content for webpack:///node_modules/react-router-dom/esm/react-router-dom.js.map: 
DevTools failed to load SourceMap: Could not load content for webpack:///node_modules/react-router/esm/react-router.js.map: 
DevTools failed to load SourceMap: Could not load content for webpack:///node_modules/uri-js/dist/es5/uri.all.js.map: 
DevTools failed to load SourceMap: Could not load content for webpack:///node_modules/performance-now/lib/performance-now.js.map: 
DevTools failed to load SourceMap: Could not load content for webpack:///node_modules/popper.js/dist/esm/popper.js.map:

**Comment by onyb** [comment]
It seems I forgot to update the Docker image. Can you please close the GUI, and try again?

**Comment by FatimaPillosu** [comment]
Sorry @onyb , the problem is still there.

Download the React DevTools for a better development experience: https://fb.me/react-devtools
You might need to use a local HTTP server (instead of file://): https://fb.me/react-devtools-faq
webpack:///../node_m…eckPropTypes.js?:20 Warning: Failed prop type: Given props { icon: "edit outline" }: Prop `children` in `Button` conflicts with props: `icon`. They cannot be defined together, choose one or the other.
    in Button (created by App)
    in App (created by ConnectFunction)
    in ConnectFunction (created by Context.Consumer)
    in Route (created by Root)
    in Switch (created by Root)
    in Router (created by HashRouter)
    in HashRouter (created by Root)
    in Root
    in PersistGate
    in Provider
webpack:///../node_m…eckPropTypes.js?:20 Warning: Failed prop type: Given props { icon: "lab" }: Prop `children` in `Button` conflicts with props: `icon`. They cannot be defined together, choose one or the other.
    in Button (created by App)
    in App (created by ConnectFunction)
    in ConnectFunction (created by Context.Consumer)
    in Route (created by Root)
    in Switch (created by Root)
    in Router (created by HashRouter)
    in HashRouter (created by Root)
    in Root
    in PersistGate
    in Provider
webpack:///../node_m…eckPropTypes.js?:20 Warning: Failed prop type: Invalid prop `color` of value `github` supplied to `Button`, expected one of ["red","orange","yellow","olive","green","teal","blue","violet","purple","pink","brown","grey","black","facebook","google plus","instagram","linkedin","twitter","vk","youtube"].
    in Button (created by App)
    in App (created by ConnectFunction)
    in ConnectFunction (created by Context.Consumer)
    in Route (created by Root)
    in Switch (created by Root)
    in Router (created by HashRouter)
    in HashRouter (created by Root)
    in Root
    in PersistGate
    in Provider
webpack:///../node_m….development.js?:88 Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: Portal
webpack:///../node_m….development.js?:88 Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: Checkbox
webpack:///../node_m….development.js?:88 Warning: validateDOMNesting(...): <div> cannot appear as a descendant of <p>.
    in div (created by Label)
    in Label (created by Predictand)
    in p (created by Predictand)
    in div (created by ItemExtra)
    in ItemExtra (created by Predictand)
    in div (created by ItemContent)
    in ItemContent (created by Predictand)
    in div (created by Item)
    in Item (created by Predictand)
    in div (created by ItemGroup)
    in ItemGroup (created by Predictand)
    in div (created by CardContent)
    in CardContent (created by Predictand)
    in div (created by Card)
    in Card (created by Predictand)
    in div (created by GridColumn)
    in GridColumn (created by Predictand)
    in div (created by Grid)
    in Grid (created by Predictand)
    in Predictand (created by ConnectFunction)
    in ConnectFunction (created by Page1)
    in Page1 (created by Page)
    in Page (created by ConnectFunction)
    in ConnectFunction (created by App)
    in App (created by ConnectFunction)
    in ConnectFunction (created by Context.Consumer)
    in Route (created by Root)
    in Switch (created by Root)
    in Router (created by HashRouter)
    in HashRouter (created by Root)
    in Root
    in PersistGate
    in Provider
webpack:///./workflo…rs/component.js?:58 Uncaught TypeError: _this.props.predictors.codes.map is not a function
    at Predictors.eval [as getField] (webpack:///./workflo…rs/component.js?:58)
    at Predictors.render (webpack:///./workflo…s/component.js?:124)
    at finishClassComponent (webpack:///../node_m…velopment.js?:17160)
    at updateClassComponent (webpack:///../node_m…velopment.js?:17110)
    at beginWork (webpack:///../node_m…velopment.js?:18620)
    at HTMLUnknownElement.callCallback (webpack:///../node_m…development.js?:188)
    at Object.invokeGuardedCallbackDev (webpack:///../node_m…development.js?:237)
    at invokeGuardedCallback (webpack:///../node_m…development.js?:292)
    at beginWork$1 (webpack:///../node_m…velopment.js?:23203)
    at performUnitOfWork (webpack:///../node_m…velopment.js?:22157)
webpack:///../node_m…velopment.js?:19527 The above error occurred in the <Predictors> component:
    in Predictors (created by ConnectFunction)
    in ConnectFunction (created by Page1)
    in Page1 (created by Page)
    in Page (created by ConnectFunction)
    in ConnectFunction (created by App)
    in App (created by ConnectFunction)
    in ConnectFunction (created by Context.Consumer)
    in Route (created by Root)
    in Switch (created by Root)
    in Router (created by HashRouter)
    in HashRouter (created by Root)
    in Root
    in PersistGate
    in Provider

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
webpack:///../node_m…velopment.js?:11102 Uncaught TypeError: _this.props.predictors.codes.map is not a function
    at Predictors.eval [as getField] (webpack:///./workflo…rs/component.js?:58)
    at Predictors.render (webpack:///./workflo…s/component.js?:124)
    at finishClassComponent (webpack:///../node_m…velopment.js?:17160)
    at updateClassComponent (webpack:///../node_m…velopment.js?:17110)
    at beginWork (webpack:///../node_m…velopment.js?:18620)
    at HTMLUnknownElement.callCallback (webpack:///../node_m…development.js?:188)
    at Object.invokeGuardedCallbackDev (webpack:///../node_m…development.js?:237)
    at invokeGuardedCallback (webpack:///../node_m…development.js?:292)
    at beginWork$1 (webpack:///../node_m…velopment.js?:23203)
    at performUnitOfWork (webpack:///../node_m…velopment.js?:22157)
DevTools failed to load SourceMap: Could not load content for webpack:///node_modules/react-router-dom/esm/react-router-dom.js.map: 
DevTools failed to load SourceMap: Could not load content for webpack:///node_modules/react-router/esm/react-router.js.map: 
DevTools failed to load SourceMap: Could not load content for webpack:///node_modules/uri-js/dist/es5/uri.all.js.map: 
DevTools failed to load SourceMap: Could not load content for webpack:///node_modules/performance-now/lib/performance-now.js.map: 
DevTools failed to load SourceMap: Could not load content for webpack:///node_modules/popper.js/dist/esm/popper.js.map:

**Comment by FatimaPillosu** [comment]
Do you wnat me to send you some gribs so you can test  the problem directly in your machine?

**Comment by onyb** [comment]
Just to make sure we're talking about the same thing, do you get the error when you try to select a directory here:
<img width="1184" alt="Screenshot 2020-10-19 at 12 42 11" src="https://user-images.githubusercontent.com/3684187/96440613-837d5700-1208-11eb-8264-08a5a36a6812.png">


To investigate further, can you send me a screenshot of what you see on your terminal? Can you also open a new tab and execute the following command, while the GUI is still open:
```
docker exec -it $(docker ps | grep "core" | awk '{ print $1 }') env | grep HOST_BINDINGS
```

**Comment by FatimaPillosu** [comment]
Hi @onyb ,
yes, we are talking about the same thing. This is exactly the point where I get a failure.

----------------------------

> Terminal screenshot (this is all what appears on my screen):

omicron{/home/mo/mofp/test}:7 --> ls
ecPoint-Calibrate-0.10.0.AppImage
omicron{/home/mo/mofp/test}:8 --> ./ecPoint-Calibrate-0.10.0.AppImage
Fontconfig warning: "/etc/fonts/fonts.conf", line 86: unknown element "blank"
Pulling from onyb/ecpoint-calibrate-core
Digest: sha256:542c1014366f8fe5b2ee86bbee9c84d8a8ad964bc4f947d18d32a33a90b006cb
Status: Image is up to date for onyb/ecpoint-calibrate-core:0.10.0
Pulling from onyb/ecpoint-calibrate-logger
Digest: sha256:2238a96fe114e3a8dc638175ed9c92d336da6b3b73394d6786554f9201b27ea9
Status: Image is up to date for onyb/ecpoint-calibrate-logger:0.10.0
Running Docker container: image=onyb/ecpoint-calibrate-core:0.10.0 containerID=08b5ae7bb12c
Running Docker container: image=onyb/ecpoint-calibrate-logger:0.10.0 containerID=3a80ab63da29
 * Serving Flask app "api" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:8888/ (Press CTRL+C to quit)
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.

----------------------------------------
Result command docker exec
`HOST_BINDINGS=/home/mo/mofp:/home,/media:/media,/vol:/vol`

**Comment by onyb** [comment]
Can we try to check this together over a call (~15 mins)? The issue is mostly like with your machine's setup. I don't think it'll be reproducible on my end even if you provide the GRIB files.

**Comment by FatimaPillosu** [comment]
Hi Anirudha,
I'm busy in a meeting until 30 pm...can we meet at 3.15 pm (londo time)?
Cheers,
Fatima

**Comment by onyb** [comment]
I won't be able to make it at that time. I am available any time on or after 4:15 PM (London time).

**Comment by FatimaPillosu** [comment]
4.15 is equally fine for me. Thanks, Fatima
